### ISSUE TITLE
Fix Card Names (encoding error???) Look for this text in the m19 set: â€”

### ISSUE THREAD

**Issue by MatteyRitch** [mtgatracker/python-mtga#1]

**Comment by MatteyRitch** [comment]
It seems to be that the "-" between some keywords (Type and Sub-Type) was extracted as â€”.
Examples: 
67686 - Ajani, Adversary of Tyrants: "Legendary Planeswalker â€” Ajani"
67718 - Knights Pledge: "Enchantment â€” Aura"

If this is a metter of just doing a find replace, I'd be happy to try and an create a branch and submit for approval later...

**Comment by Spencatro** [comment]
Fixed in mtga `0.2.0`, thank you!
