### ISSUE TITLE
Dominaria code "DAR" instead of "DOM"

### ISSUE THREAD

**Issue by bhughes339** [mtgatracker/python-mtga#10]
Just wondering if there's a reason that the code for Dominaria was changed from DOM to DAR in commit 5c2c103746b00658e483c5b281b1007d83a2a1be or if it was a mistake. Thanks!

**Comment by Spencatro** [comment]
It's intentional. It's not clear exactly why, but MTGA internally refers to the Dominaria set with the short code DAR. Maybe that was it's short code during development.
