### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by kelesi** [mtgatracker/python-mtga#2]
Running
`pip install mtga`
fails with

> λ pip install mtga
Collecting mtga
  Using cached https://files.pythonhosted.org/packages/e0/1d/7d0fc1acca2de171c14db37ec3d0d17d0c748707492d30dc58c15848fd9b/mtga-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\dweller\appdata\local\temp\pip-install-ejqvif\mtga\setup.py", line 78, in <module>
        with open("major_version") as f:
    IOError: [Errno 2] No such file or directory: 'major_version'

Tried on windows with python 2.7.13

**Comment by Spencatro** [comment]
yikes, thanks for the report. embarrassing that got out, will fix by end of day

**Comment by Spencatro** [comment]
Note: I had to change git commit history (related to, but not because of) this issue. If you're using `mtga` from source, please remove and re-clone it (or, if you know how to detach and delete your master branch, that works too)

**Comment by kelesi** [comment]
Thanks!

**Comment by kelesi** [comment]
Install via pip still fails. The bundle does not contain requirements.txt.
Please check my PR.
`Collecting mtga
  Downloading https://files.pythonhosted.org/packages/30/08/49c672820f8ff14083e1522047be3f0d06ad8382bfdbd1643fcc8afebdee/MTGA-0.4.2.tar.gz (92kB)
    100% |################################| 102kB 939kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\dweller\appdata\local\temp\pip-install-uksc47\mtga\setup.py", line 53, in <module>
        _install_requires = read_requirements_file('requirements.txt')
      File "c:\users\dweller\appdata\local\temp\pip-install-uksc47\mtga\setup.py", line 28, in read_requirements_file
        with open(path) as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
`
