### ISSUE TITLE
Ikoria update breaks card import

### ISSUE THREAD

**Issue by pak21** [mtgatracker/python-mtga#24]
The Ikoria release of Arena (2020-04-16) breaks the card importer in two ways:
 
* They've removed the `isCollectible` field from the data files. I haven't found a replacement yet :-(
* One (and only one) card (grpId 73649, which I think is the premium skin of Mysterious Egg) is missing the `CollectorNumber` field. Looking at its location in the file, it fairly obviously should be 385.

**Comment by rrwoods** [comment]
I just noticed this as well.  There's a PR open that fixes this issue already, but it isn't merged to master: https://github.com/mtgatracker/python-mtga/pull/23

**Comment by pak21** [comment]
Fixed by the changes in #23, closing.
