### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by micku** [mtgatracker/python-mtga#26]
I see issues not addressed from a long time and a bounch of PRs waiting for approval.

I'm about to post a PR adding the support for macOS client, but I'm almost sure this won't be merged, so I can't use other projects that rely on this without pointing to my fork.

Other issues:
- The [Pypi entry](https://pypi.org/project/MTGA/) points to [the wrong repo](https://github.com/mtgatracker/mtgatracker);
- No documentation at all.

I will be glad to contribute!

**Comment by Spencatro** [comment]
I've fixed the readme and PyPI entry (edit: in version 0.9.5). Adding documentation is a task I'm not really up for right now :)

To be frank, I don't have the time to maintain these projects and thoroughly as I used to. Please shoot me an email at devs.mtgatracker@gmail.com if you're interested in help maintain any mtgatracker projects!
