### ISSUE TITLE
Missing three ids: 69449, 69450, 69451 (likely the closed beta rewards?)

### ISSUE THREAD

**Issue by milopiccolo** [mtgatracker/python-mtga#4]
Thank you for this package!

My collection contains the three closed beta reward cards, and when I used https://github.com/kelesi/mtga-utils to try to scrape my collection, these three ids were not found in the pool, so they probably pertain to those cards!

I don't know which is which, but these are the names: 
'As a thank you, every player who participated in the Closed Beta will receive one digital copy each of three cards from Guilds of Ravnica: Mythic Edition: Teferi, Hero of Dominaria; Ral, Izzet Viceroy; and Vraska, Gorgon Queen.'

**Comment by Spencatro** [comment]
Thanks for the report! We're also tracking this issue here https://github.com/mtgatracker/mtgatracker/issues/307 and hope to have it resolved by the end of the day.

**Comment by Spencatro** [comment]
fixed in https://pypi.org/project/MTGA/0.4.1/ :)
